---
title: "Aquisição de Arquivos e Datasets"
author: "Delermando Branquinho Filho"
output: pdf_document
subtitle: Subset e Ordenação
job: The Scientist
---


## Subsetting - Revisão rápida

```{r subsetting}
set.seed(13435)
X <- data.frame("var1"=sample(1:5),"var2"=sample(6:10),"var3"=sample(11:15))
X <- X[sample(1:5),]; X$var2[c(1,3)] = NA
X
```


```{r ,dependson="subsetting"}
X[,1]
X[,"var1"]
X[1:2,"var2"]
```


---

## Logico "e"  "ou"

```{r ,dependson="subsetting"}
X[(X$var1 <= 3 & X$var3 > 11),]
X[(X$var1 <= 3 | X$var3 > 15),]
```

---

## Lidar com valores em falta

```{r ,dependson="subsetting"}
X[which(X$var2 > 8),]
```

---

## Sorting

```{r ,dependson="subsetting"}
sort(X$var1)
sort(X$var1,decreasing=TRUE)
sort(X$var2,na.last=TRUE)
```


---

## Ordering

```{r ,dependson="subsetting"}
X[order(X$var1),]
```


```{r ,dependson="subsetting"}
X[order(X$var1,X$var3),]
```

---

## Ordenando com plyr

```{r ,dependson="subsetting"}
library(plyr)
arrange(X,var1)
arrange(X,desc(var1))
```


---

## Adicionando linhas e colunas

```{r,dependson="subsetting"}
X$var4 <- rnorm(5)
X
```


```{r,dependson="subsetting"}
Y <- cbind(X,rnorm(5))
Y
```



