---
title: "Aquisição de Arquivos e Datasets"
author: "Delermando Branquinho Filho"
output: pdf_document
subtitle: Sumarizando Dados
job: The Scientist
---

``


## Dataset Exemplo

## Getting the data from the web

```{r getData, warning=FALSE}
if(!file.exists("./data")){dir.create("./data")}
fileUrl <- "https://data.baltimorecity.gov/api/views/k5ry-ef3g/rows.csv?accessType=DOWNLOAD"
download.file(fileUrl,destfile="./data/restaurants.csv",method="curl")
restData <- read.csv("./data/restaurants.csv")
```


---

## Olhe para um pouco dos dados

```{r ,dependson="getData"}
head(restData,n=3)
tail(restData,n=3)
```


---

## Fazer resumo

```{r ,dependson="getData"}
summary(restData)
```

---

## Mais informações detalhadas

```{r ,dependson="getData"}
str(restData)
```


---

## Variáveis quantitativas

```{r ,dependson="getData"}
quantile(restData$councilDistrict,na.rm=TRUE)
quantile(restData$councilDistrict,probs=c(0.5,0.75,0.9))
```

---

## Fazendo tabelas

```{r ,dependson="getData"}
table(restData$zipCode,useNA="ifany")
```



```{r ,dependson="getData"}
table(restData$councilDistrict,restData$zipCode)
```

---

## Verificar se há valores em falta

```{r ,dependson="getData"}
sum(is.na(restData$councilDistrict))
any(is.na(restData$councilDistrict))
all(restData$zipCode > 0)
```


---

## Somas de linhas e colunas

```{r,dependson="getData"}
colSums(is.na(restData))
all(colSums(is.na(restData))==0)
```


---

## Valores com características específicas

```{r,dependson="getData"}
table(restData$zipCode %in% c("21212"))
table(restData$zipCode %in% c("21212","21213"))

```



```{r,dependson="getData"}
restData[restData$zipCode %in% c("21212","21213"),]
```


---

## Cross tabs

```{r adm}
data(UCBAdmissions)
DF = as.data.frame(UCBAdmissions)
summary(DF)
```




```{r ,dependson="adm"}
xt <- xtabs(Freq ~ Gender + Admit,data=DF)
xt
```


---

## Flat tables

```{r wb}
warpbreaks$replicate <- rep(1:9, len = 54)
xt = xtabs(breaks ~.,data=warpbreaks)
xt

```


---

## Flat tables

```{r ,dependson="wb"}
ftable(xt)
```


---

## Tamanho de um conjunto de dados

```{r}
fakeData = rnorm(1e5)
object.size(fakeData)
print(object.size(fakeData),units="Mb")
```






