---
title       : Pesquisa Reprodutível
subtitle    : MarkDown II
author      : Delermando Branquinho Filho
output: pdf_document
job: The Scientist
---
## O que é o Markdown?

* Criado por [John Gruber] (http://daringfireball.net) e Aaron Swartz

* Uma versão simplificada de linguagens de "marcação"

* Permite que um se concentre na escrita ao contrário da formatação

* Elementos de formatação intuitivos simples / mínimos

* Facilmente convertido em HTML válido (e outros formatos) usando ferramentas existentes

* Informações completas estão disponíveis em [http://daringfireball.net/projects/markdown/](http://daringfireball.net/projects/markdown/)

* Algumas informações gerais em [http://daringfireball.net/2004/03/dive_into_markdown](http://daringfireball.net/2004/03/dive_into_markdown)
---
## O que é R Markdown?

* R markdown é a integração do código R com markdown

* Permite a criação de documentos contendo "vivo" código R

* O código R é avaliado como parte do processamento do

* Os resultados do código R são inseridos no documento de

* Uma ferramenta central na <b> programação literária alfabetizada </ b>

## O que é R Markdown?

* O markdown de R pode ser convertido em markdown padrão usando o [Knitr](http://yihui.name/knitr/) pacote em R

* Markdown pode ser convertido em HTML usando o pacote [markdown] (https://github.com/rstudio/markdown) em R

* Qualquer editor de texto básico pode ser usado para criar um documento markdown; não são ferramentas especiais de edição necessárias

* O markdown de R -> markdown -> fluxo de trabalho HTML pode ser facilmente gerenciado usando [R Studio] (http://rstudio.org) (mas não obrigatório)

* Você pode escrever em markdown R e o converter em slides usando o pacote [slidify] (http://slidify.org)

